<template>
    <RPin
        name="curto"
        label="~~:length=&quot;4&quot;"
        :length="4"
    />
    <RPin
        name="longo"
        label="~~:length=&quot;8&quot;"
        :length="8"
    />
</template>