<template>
    <RPin
        name="numerico"
        label='~~type="numeric"'
        type="numeric"
    />
    <RPin
        name="alfanumerico"
        label='~~type="alphanumeric"'
        type="alphanumeric"
        :length="5"
    />
</template>