<template>
    <RNumber
        name="carregando"
        label="demo.common.carregando"
        loading
    />
    <RNumber
        name="comErro"
        label="demo.common.erroManual"
        :error="$t('demo.number.erro')"
    />
</template>