<template>
    <RNumber
        name="carregando"
        label="demo.common.carregando"
        loading
    />
    <RNumber
        name="comErro"
        label="demo.common.erroManual"
        error="demo.number.erro"
    />
</template>