<template>
    <RText
        name="cpf"
        label="~~brCpf"
        mask="brCpf"
    />
    <RText
        name="cnpj"
        label="~~brCnpj"
        mask="brCnpj"
    />
    <RText
        name="cep"
        label="~~brCep"
        mask="brCep"
    />
    <RText
        name="telefone"
        label="~~brTelefone"
        mask="brTelefone"
    />
    <RText
        name="celular"
        label="~~brCelular"
        mask="brCelular"
    />
    <RText
        name="cpfCnpj"
        label="~~brCpfCnpj"
        mask="brCpfCnpj"
    />
    <RText
        name="placa"
        label="~~brPlaca"
        mask="brPlaca"
    />
    <RText
        name="data"
        label="~~brData"
        mask="brData"
    />
</template>