<template>
    <RColor
        name="obrigatoria"
        label="demo.common.obrigatorio"
        required
        rule="required"
    />
    <RColor
        name="carregando"
        label="demo.common.carregando"
        loading
    />
    <RColor
        name="comErro"
        label="demo.common.erroManual"
        error="demo.color.erro"
    />
</template>