<template>
    <RTextarea
        name="dinheiroArea"
        label='~~mask="dinheiro"'
        mask="dinheiro"
        :rows="2"
    />
    <RTextarea
        name="cpfArea"
        label='~~mask="brCpf"'
        mask="brCpf"
        :rows="2"
    />
</template>