<template>
    <RText
        name="carregando"
        label="demo.text.carregando"
        loading
    />
    <RText
        name="comErro"
        label="demo.text.erroManual"
        error="demo.text.erroMensagem"
    />
</template>